

# --- RL hyperparameters ---



# --- Agent parameters ---
#agent: "rnn" # Default rnn agent
#hidden_dim: 64 # Size of hidden state for default rnn agent
#obs_agent_id: True # Include the agent's one_hot id in the observation
#obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
#repeat_id: 1
#label: "default_label"
#hypergroup: null
# ---CommNet specific args---
commnet: True #enable commnet model


name: "commnet"