env: "tj"
n_agents: 10
dim: 14
max_steps: 40
add_rate_min: 0.2
add_rate_max: 0.2
difficulty: medium
vision: 1
nprocess: 16
num_epochs: 2000
epoch_size: 10
hid_size: 128
detach_gap: 10
curr_start: 0
curr_end: 0
vocab_type: bool
