

# --- RL hyperparameters ---


# --- Agent parameters ---
#agent: "rnn" # Default rnn agent
#hidden_dim: 64 # Size of hidden state for default rnn agent
#obs_agent_id: True # Include the agent's one_hot id in the observation
#obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
#repeat_id: 1
#label: "default_label"
#hypergroup: null
# ---CommNet specific args---




mean_ratio: 0 #how much coooperative to do? 1.0 means fully cooperative


# ---magic specific args---
magic: True
directed: False #whether the communication graph is directed
self_loop_type1: 2 #self loop type in the first gat layer (0: no self loop, 1: with self loop, 2: decided by hard attn mechanism)
self_loop_type2: 2 #self loop type in the second gat layer (0: no self loop, 1: with self loop, 2: decided by hard attn mechanism)
gat_num_heads: 1 #number of heads in gat layers except the last one
gat_num_heads_out: 1 #number of heads in output gat layer
gat_hid_size: 64 #hidden size of one head in gat
ge_num_heads: 4 #number of heads in the gat encoder
first_gat_normalize: False #whether normalize the coefficients in the first gat layer of the message processor
second_gat_normalize: False #whether normilize the coefficients in the second gat layer of the message proccessor
gat_encoder_normalize: False #whether normilize the coefficients in the gat encoder (they have been normalized if the input graph is complete
use_gat_encoder: False #whether use the gat encoder before learning the first graph
gat_encoder_out_size: 64 #hidden size of output of the gat encoder
first_graph_complete: False #whether the first communication graph is set to a complete graph
second_graph_complete: False #whether the second communication graph is set to a complete graph
learn_second_graph: False #whether learn a new communication graph at the second round of communication
message_encoder: False #whether use the message encoder
message_decoder: False #whether use the message decoder







name: "magic"
